package com.example.ui.screens

import androidx.compose.animation.*
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material.icons.outlined.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathEffect
import androidx.compose.ui.platform.LocalClipboardManager
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.text.AnnotatedString
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.ui.theme.T
import com.example.ui.viewmodel.PesoWalletViewModel
import java.util.UUID

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun SendScreen(viewModel: PesoWalletViewModel, modifier: Modifier = Modifier) {
    val lang by viewModel.currentLanguage.collectAsState()
    val assets by viewModel.assets.collectAsState()
    val activeNetwork by viewModel.defaultNetwork.collectAsState()

    var step by remember { mutableStateOf(1) } // 1 = Details input, 2 = Review, 3 = Receipt

    // Form inputs
    var recipientAddress by remember { mutableStateOf("") }
    var recipientName by remember { mutableStateOf("") }
    var sendAmount by remember { mutableStateOf("") }
    var sendNote by remember { mutableStateOf("") }
    var selectedAssetSymbol by remember { mutableStateOf("UXD") }
    var selectedCategory by remember { mutableStateOf("Transferencia") }
    var txError by remember { mutableStateOf<String?>(null) }
    var txHashGenerated by remember { mutableStateOf("") }

    val clipboard = LocalClipboardManager.current

    Box(
        modifier = modifier
            .fillMaxSize()
            .background(Color(0xFF090D16))
            .windowInsetsPadding(WindowInsets.statusBars)
    ) {
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(16.dp)
        ) {
            // Header
            Row(
                modifier = Modifier.fillMaxWidth(),
                verticalAlignment = Alignment.CenterVertically
            ) {
                IconButton(onClick = {
                    if (step > 1 && step < 3) {
                        step--
                    } else {
                        viewModel.navigateTo("dashboard")
                    }
                }) {
                    Icon(imageVector = Icons.Default.ArrowBack, contentDescription = "Back", tint = Color.White)
                }
                Spacer(modifier = Modifier.width(8.dp))
                Text(
                    text = T.translate(lang, "send_stable"),
                    style = MaterialTheme.typography.titleLarge.copy(fontWeight = FontWeight.Bold),
                    color = Color.White
                )
            }

            Spacer(modifier = Modifier.height(16.dp))

            when (step) {
                1 -> {
                    // STEP 1: Form details Input
                    Column(
                        modifier = Modifier
                            .weight(1f)
                            .verticalScroll(rememberScrollState()),
                        verticalArrangement = Arrangement.spacedBy(16.dp)
                    ) {
                        // Recipient Address Input
                        OutlinedTextField(
                            value = recipientAddress,
                            onValueChange = {
                                recipientAddress = it
                                // Fast alias lookup simulation
                                if (it.contains(".") && recipientName.isEmpty()) {
                                    recipientName = it.substringBefore(".").replaceFirstChar { char -> char.uppercase() } + " " + (if (it.endsWith(".mp")) "MercadoPago" else "Wallet")
                                }
                            },
                            label = { Text(text = T.translate(lang, "enter_address"), color = Color.White.copy(alpha = 0.6f)) },
                            leadingIcon = { Icon(imageVector = Icons.Default.AlternateEmail, contentDescription = null, tint = Color(0xFF007AFA)) },
                            trailingIcon = {
                                IconButton(onClick = {
                                    recipientAddress = "mariana.usdt"
                                    recipientName = "Mariana Sanguinetti"
                                }) {
                                    Icon(imageVector = Icons.Default.ContactPage, contentDescription = "Contacts", tint = Color.White.copy(alpha = 0.6f))
                                }
                            },
                            colors = TextFieldDefaults.outlinedTextFieldColors(
                                focusedTextColor = Color.White,
                                unfocusedTextColor = Color.White,
                                focusedBorderColor = Color(0xFF007AFA),
                                unfocusedBorderColor = Color(0xFF1E293B)
                            ),
                            modifier = Modifier
                                .fillMaxWidth()
                                .testTag("send_address_field"),
                            maxLines = 1
                        )

                        // Name Input
                        OutlinedTextField(
                            value = recipientName,
                            onValueChange = { recipientName = it },
                            label = { Text(text = "Nombre del Destinatario (Opcional)", color = Color.White.copy(alpha = 0.6f)) },
                            colors = TextFieldDefaults.outlinedTextFieldColors(
                                focusedTextColor = Color.White,
                                unfocusedTextColor = Color.White,
                                focusedBorderColor = Color(0xFF007AFA),
                                unfocusedBorderColor = Color(0xFF1E293B)
                            ),
                            modifier = Modifier.fillMaxWidth()
                        )

                        // Asset selection cards list row
                        Text(text = "Seleccionar Moneda:", color = Color.White.copy(alpha = 0.8f), fontWeight = FontWeight.SemiBold)
                        Row(
                            horizontalArrangement = Arrangement.spacedBy(8.dp),
                            modifier = Modifier.fillMaxWidth()
                        ) {
                            val listAssets = listOf("UXD", "USDT", "ARS", "crypto-ARS")
                            listAssets.forEach { sym ->
                                val isSelected = selectedAssetSymbol == sym
                                Card(
                                    modifier = Modifier
                                        .weight(1f)
                                        .clickable { selectedAssetSymbol = sym },
                                    border = BorderStroke(1.dp, if (isSelected) Color(0xFF007AFA) else Color(0xFF1E293B)),
                                    colors = CardDefaults.cardColors(containerColor = if (isSelected) Color(0xFF0E2540) else Color(0xFF131B2A))
                                ) {
                                    Box(
                                        modifier = Modifier
                                            .padding(vertical = 12.dp)
                                            .fillMaxWidth(),
                                        contentAlignment = Alignment.Center
                                    ) {
                                        Text(text = sym, color = if (isSelected) Color(0xFF4FA9FB) else Color.White, fontWeight = FontWeight.Bold, fontSize = 14.sp)
                                    }
                                }
                            }
                        }

                        // Amount Input
                        OutlinedTextField(
                            value = sendAmount,
                            onValueChange = { sendAmount = it },
                            label = { Text(text = T.translate(lang, "amount"), color = Color.White.copy(alpha = 0.6f)) },
                            placeholder = { Text(text = "0.00", color = Color.White.copy(alpha = 0.3f)) },
                            suffix = { Text(text = selectedAssetSymbol, color = Color(0xFF4FA9FB), fontWeight = FontWeight.Bold) },
                            keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Decimal),
                            colors = TextFieldDefaults.outlinedTextFieldColors(
                                focusedTextColor = Color.White,
                                unfocusedTextColor = Color.White,
                                focusedBorderColor = Color(0xFF007AFA),
                                unfocusedBorderColor = Color(0xFF1E293B)
                            ),
                            modifier = Modifier
                                .fillMaxWidth()
                                .testTag("send_amount_field")
                        )

                        // Note / Bill details Input
                        OutlinedTextField(
                            value = sendNote,
                            onValueChange = { sendNote = it },
                            label = { Text(text = T.translate(lang, "note"), color = Color.White.copy(alpha = 0.6f)) },
                            colors = TextFieldDefaults.outlinedTextFieldColors(
                                focusedTextColor = Color.White,
                                unfocusedTextColor = Color.White,
                                focusedBorderColor = Color(0xFF007AFA),
                                unfocusedBorderColor = Color(0xFF1E293B)
                            ),
                            modifier = Modifier.fillMaxWidth()
                        )

                        // Category Options Row
                        Text(text = "Categoría:", color = Color.White.copy(alpha = 0.8f), fontSize = 13.sp)
                        Row(
                            horizontalArrangement = Arrangement.spacedBy(8.dp),
                            modifier = Modifier.fillMaxWidth()
                        ) {
                            val cats = listOf("Transferencia", "Servicios", "Alimentos", "Ahorro", "Varios")
                            cats.forEach { cat ->
                                val isSelected = selectedCategory == cat
                                Box(
                                    modifier = Modifier
                                        .clip(RoundedCornerShape(8.dp))
                                        .background(if (isSelected) Color(0xFF007AFA) else Color(0xFF1E293B))
                                        .clickable { selectedCategory = cat }
                                        .padding(horizontal = 12.dp, vertical = 6.dp)
                                ) {
                                    Text(text = cat, fontSize = 11.sp, fontWeight = FontWeight.Bold, color = Color.White)
                                }
                            }
                        }
                    }

                    // Continue button
                    Button(
                        onClick = {
                            val amount = sendAmount.toDoubleOrNull()
                            if (recipientAddress.isEmpty()) {
                                txError = "Por favor, ingresá un destinatario."
                            } else if (amount == null || amount <= 0) {
                                txError = "Monto inválido."
                            } else {
                                txError = null
                                step = 2 // Move on to review
                            }
                        },
                        colors = ButtonDefaults.buttonColors(containerColor = Color(0xFF007AFA)),
                        shape = RoundedCornerShape(12.dp),
                        modifier = Modifier
                            .fillMaxWidth()
                            .height(56.dp)
                            .testTag("send_continue_button")
                    ) {
                        Text(text = T.translate(lang, "next"), fontWeight = FontWeight.Bold, fontSize = 16.sp)
                    }
                }

                2 -> {
                    // STEP 2: REVIEW TRANSACTION
                    Column(
                        modifier = Modifier.weight(1f),
                        verticalArrangement = Arrangement.spacedBy(16.dp)
                    ) {
                        Text(text = T.translate(lang, "review_tx"), style = MaterialTheme.typography.titleMedium.copy(fontWeight = FontWeight.Bold), color = Color.White)

                        Card(
                            shape = RoundedCornerShape(16.dp),
                            colors = CardDefaults.cardColors(containerColor = Color(0xFF131B2A)),
                            modifier = Modifier.fillMaxWidth()
                        ) {
                            Column(
                                modifier = Modifier.padding(16.dp),
                                verticalArrangement = Arrangement.spacedBy(12.dp)
                            ) {
                                Row(
                                    modifier = Modifier.fillMaxWidth(),
                                    horizontalArrangement = Arrangement.SpaceBetween
                                ) {
                                    Text(text = T.translate(lang, "sending_to"), color = Color.Gray)
                                    Text(text = recipientName.ifEmpty { recipientAddress }, fontWeight = FontWeight.Bold, color = Color.White)
                                }
                                Row(
                                    modifier = Modifier.fillMaxWidth(),
                                    horizontalArrangement = Arrangement.SpaceBetween
                                ) {
                                    Text(text = "Destinatario Key", color = Color.Gray)
                                    Text(text = recipientAddress, fontSize = 12.sp, color = Color.White.copy(alpha = 0.6f))
                                }
                                Row(
                                    modifier = Modifier.fillMaxWidth(),
                                    horizontalArrangement = Arrangement.SpaceBetween
                                ) {
                                    Text(text = T.translate(lang, "network"), color = Color.Gray)
                                    Text(text = activeNetwork, color = Color(0xFF4FA9FB), fontWeight = FontWeight.Bold)
                                }
                                Row(
                                    modifier = Modifier.fillMaxWidth(),
                                    horizontalArrangement = Arrangement.SpaceBetween
                                ) {
                                    Text(text = T.translate(lang, "category"), color = Color.Gray)
                                    Text(text = selectedCategory, color = Color.White)
                                }

                                Divider(color = Color.White.copy(alpha = 0.1f))

                                Row(
                                    modifier = Modifier.fillMaxWidth(),
                                    horizontalArrangement = Arrangement.SpaceBetween,
                                    verticalAlignment = Alignment.CenterVertically
                                ) {
                                    Text(text = T.translate(lang, "amount"), color = Color.Gray)
                                    Text(text = "$sendAmount $selectedAssetSymbol", fontWeight = FontWeight.Bold, color = Color.White, fontSize = 18.sp)
                                }

                                Row(
                                    modifier = Modifier.fillMaxWidth(),
                                    horizontalArrangement = Arrangement.SpaceBetween
                                ) {
                                    Text(text = T.translate(lang, "fee"), color = Color.Gray)
                                    val fee = if (activeNetwork == "Ethereum Mainnet") "2.50 UXD" else "0.02 UXD"
                                    Text(text = fee, color = Color.Gray)
                                }
                            }
                        }

                        Spacer(modifier = Modifier.weight(1f))

                        if (txError != null) {
                            Text(text = txError!!, color = Color.Red, modifier = Modifier.fillMaxWidth(), textAlign = TextAlign.Center)
                        }

                        // Simulated Swipe Action Slider button
                        var sliderPosition by remember { mutableStateOf(0.1f) }
                        Column(
                            modifier = Modifier.fillMaxWidth(),
                            horizontalAlignment = Alignment.CenterHorizontally
                        ) {
                            Text(text = "Deslizar para confirmar pago ═══▶", fontSize = 12.sp, color = Color.White.copy(alpha = 0.6f), fontWeight = FontWeight.SemiBold)
                            Slider(
                                value = sliderPosition,
                                onValueChange = {
                                    sliderPosition = it
                                    if (it >= 0.9f) {
                                        // Trigger send operation
                                        val amt = sendAmount.toDoubleOrNull() ?: 0.0
                                        viewModel.sendTransaction(
                                            selectedAssetSymbol,
                                            recipientName.ifEmpty { recipientAddress },
                                            recipientAddress,
                                            amt,
                                            sendNote,
                                            activeNetwork,
                                            selectedCategory
                                        ) { res ->
                                            if (res.isSuccess) {
                                                txHashGenerated = "0x" + UUID.randomUUID().toString().replace("-", "").take(32)
                                                step = 3
                                            } else {
                                                txError = res.exceptionOrNull()?.message ?: "Surgió un error inesperado de saldo."
                                                sliderPosition = 0.1f
                                            }
                                        }
                                    }
                                },
                                valueRange = 0.1f..1.0f,
                                colors = SliderDefaults.colors(
                                    thumbColor = Color(0xFF007AFA),
                                    activeTrackColor = Color(0xFF007AFA).copy(alpha = 0.4f),
                                    inactiveTrackColor = Color(0xFF1E293B)
                                ),
                                modifier = Modifier
                                    .padding(vertical = 12.dp)
                                    .testTag("confirm_slider")
                            )
                        }
                    }
                }

                3 -> {
                    // STEP 3: TRANSACTION RECEIPT VOUCHER
                    Column(
                        modifier = Modifier
                            .weight(1f)
                            .verticalScroll(rememberScrollState()),
                        horizontalAlignment = Alignment.CenterHorizontally,
                        verticalArrangement = Arrangement.spacedBy(16.dp)
                    ) {
                        Box(
                            modifier = Modifier
                                .size(72.dp)
                                .clip(CircleShape)
                                .background(Color(0xFF1E3A24)),
                            contentAlignment = Alignment.Center
                        ) {
                            Icon(imageVector = Icons.Default.Check, contentDescription = null, tint = Color(0xFF4CAF50), modifier = Modifier.size(36.dp))
                        }

                        Text(
                            text = T.translate(lang, "payment_success"),
                            style = MaterialTheme.typography.titleLarge.copy(fontWeight = FontWeight.Bold),
                            color = Color.White,
                            textAlign = TextAlign.Center
                        )

                        // Ticket details with custom Canvas dashes (classic receipt detail)
                        Card(
                            shape = RoundedCornerShape(16.dp),
                            colors = CardDefaults.cardColors(containerColor = Color(0xFF131B2A)),
                            modifier = Modifier.fillMaxWidth()
                        ) {
                            Column(
                                modifier = Modifier.padding(16.dp),
                                verticalArrangement = Arrangement.spacedBy(12.dp)
                            ) {
                                Row(
                                    modifier = Modifier.fillMaxWidth(),
                                    horizontalArrangement = Arrangement.SpaceBetween
                                ) {
                                    Text(text = "Comprobante", color = Color.Gray)
                                    Text(text = "#PW-" + txHashGenerated.take(6).uppercase(), fontWeight = FontWeight.Bold, color = Color.White)
                                }

                                Row(
                                    modifier = Modifier.fillMaxWidth(),
                                    horizontalArrangement = Arrangement.SpaceBetween
                                ) {
                                    Text(text = "Hacia", color = Color.Gray)
                                    Text(text = recipientName.ifEmpty { recipientAddress }, color = Color.White)
                                }

                                Row(
                                    modifier = Modifier.fillMaxWidth(),
                                    horizontalArrangement = Arrangement.SpaceBetween
                                ) {
                                    Text(text = "Monto enviado", color = Color.Gray)
                                    Text(text = "$sendAmount $selectedAssetSymbol", fontWeight = FontWeight.Bold, color = Color.White, fontSize = 20.sp)
                                }

                                Row(
                                    modifier = Modifier.fillMaxWidth(),
                                    horizontalArrangement = Arrangement.SpaceBetween
                                ) {
                                    Text(text = T.translate(lang, "network"), color = Color.Gray)
                                    Text(text = activeNetwork, color = Color.Gray)
                                }

                                Row(
                                    modifier = Modifier.fillMaxWidth(),
                                    horizontalArrangement = Arrangement.SpaceBetween
                                ) {
                                    Text(text = "TX Hash", color = Color.Gray)
                                    Text(text = txHashGenerated.take(16) + "...", color = Color.Gray, fontSize = 11.sp)
                                }
                            }
                        }

                        // Close button returning home
                        Button(
                            onClick = { viewModel.navigateTo("dashboard") },
                            colors = ButtonDefaults.buttonColors(containerColor = Color(0xFF131B2A)),
                            shape = RoundedCornerShape(12.dp),
                            modifier = Modifier
                                .fillMaxWidth()
                                .height(56.dp)
                        ) {
                            Text(text = "Regresar al Inicio")
                        }
                    }
                }
            }

            if (txError != null && step < 2) {
                Text(text = txError!!, color = Color.Red, modifier = Modifier.padding(vertical = 8.dp), textAlign = TextAlign.Center)
            }
        }
    }
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun ReceiveScreen(viewModel: PesoWalletViewModel, modifier: Modifier = Modifier) {
    val lang by viewModel.currentLanguage.collectAsState()
    val activeNetwork by viewModel.defaultNetwork.collectAsState()

    var requestAmount by remember { mutableStateOf("") }
    var selectedAssetSymbol by remember { mutableStateOf("UXD") }
    var showCustomQr by remember { mutableStateOf(false) }

    val mockAddress = "0x89Ef27635Bc8c42a27b87F635dC2B0A95648f572"
    val clipboard = LocalClipboardManager.current

    Box(
        modifier = modifier
            .fillMaxSize()
            .background(Color(0xFF090D16))
            .windowInsetsPadding(WindowInsets.statusBars)
    ) {
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(16.dp),
            horizontalAlignment = Alignment.CenterHorizontally
        ) {
            // Header
            Row(
                modifier = Modifier.fillMaxWidth(),
                verticalAlignment = Alignment.CenterVertically
            ) {
                IconButton(onClick = { viewModel.navigateTo("dashboard") }) {
                    Icon(imageVector = Icons.Default.ArrowBack, contentDescription = "Back", tint = Color.White)
                }
                Spacer(modifier = Modifier.width(8.dp))
                Text(
                    text = T.translate(lang, "receive_stable"),
                    style = MaterialTheme.typography.titleLarge.copy(fontWeight = FontWeight.Bold),
                    color = Color.White
                )
            }

            Spacer(modifier = Modifier.height(24.dp))

            // Beautiful QR representation with Canvas & Dashes (to bypass needing complex QR rendering lib!)
            Card(
                shape = RoundedCornerShape(24.dp),
                colors = CardDefaults.cardColors(containerColor = Color(0xFF131B2A)),
                modifier = Modifier
                    .size(280.dp)
                    .padding(8.dp),
                border = BorderStroke(1.dp, Color(0xFF1E293B))
            ) {
                Box(
                    modifier = Modifier.fillMaxSize(),
                    contentAlignment = Alignment.Center
                ) {
                    // Modern Styled grid blocks resembling QR code
                    Canvas(modifier = Modifier.size(200.dp)) {
                        val gridSize = 10
                        val cellSize = size.width / gridSize
                        val brushColors = listOf(Color(0xFF2196F3), Color(0xFF00E5FF))
                        
                        // Fake QR corners (eyes)
                        drawRect(Color(0xFF007AFA), Offset(0f, 0f), size = androidx.compose.ui.geometry.Size(cellSize * 3, cellSize * 3))
                        drawRect(Color.White, Offset(cellSize, cellSize), size = androidx.compose.ui.geometry.Size(cellSize, cellSize))

                        drawRect(Color(0xFF007AFA), Offset(cellSize * 7, 0f), size = androidx.compose.ui.geometry.Size(cellSize * 3, cellSize * 3))
                        drawRect(Color.White, Offset(cellSize * 8, cellSize), size = androidx.compose.ui.geometry.Size(cellSize, cellSize))

                        drawRect(Color(0xFF007AFA), Offset(0f, cellSize * 7), size = androidx.compose.ui.geometry.Size(cellSize * 3, cellSize * 3))
                        drawRect(Color.White, Offset(cellSize, cellSize * 8), size = androidx.compose.ui.geometry.Size(cellSize, cellSize))

                        // Scattered digital points dynamically if custom QR activated
                        for (x in 2..7) {
                            for (y in 2..7) {
                                if ((x + y + (if (showCustomQr) requestAmount.length else 3)) % 3 == 0) {
                                    drawRect(Color(0xFF00E5FF), Offset(x * cellSize, y * cellSize), size = androidx.compose.ui.geometry.Size(cellSize * 0.8f, cellSize * 0.8f))
                                }
                            }
                        }
                    }
                    
                    // Floating Center logo
                    Box(
                        modifier = Modifier
                            .size(40.dp)
                            .clip(CircleShape)
                            .background(Color(0xFF131B2A))
                            .border(2.dp, Color(0xFF007AFA), CircleShape),
                        contentAlignment = Alignment.Center
                    ) {
                        Text(text = "PW", color = Color.White, fontWeight = FontWeight.Bold, fontSize = 12.sp)
                    }
                }
            }

            Spacer(modifier = Modifier.height(16.dp))

            // Balance Details description
            Text(
                text = "${T.translate(lang, "your_address")} (Red: $activeNetwork)",
                fontSize = 11.sp,
                color = Color.White.copy(alpha = 0.5f)
            )

            Row(
                modifier = Modifier
                    .fillMaxWidth(0.9f)
                    .clip(RoundedCornerShape(8.dp))
                    .background(Color(0xFF1E293B))
                    .clickable {
                        clipboard.setText(AnnotatedString(mockAddress))
                    }
                    .padding(8.dp),
                verticalAlignment = Alignment.CenterVertically,
                horizontalArrangement = Arrangement.SpaceBetween
            ) {
                Text(
                    text = "0x89Ef...572",
                    fontSize = 13.sp,
                    color = Color.White,
                    fontWeight = FontWeight.SemiBold,
                    modifier = Modifier.weight(1f),
                    textAlign = TextAlign.Center
                )
                Icon(imageVector = Icons.Default.ContentCopy, contentDescription = "Copy", tint = Color(0xFF007AFA), modifier = Modifier.size(16.dp))
            }

            Spacer(modifier = Modifier.height(24.dp))

            // Dynamic Invoice Generator fields
            Card(
                shape = RoundedCornerShape(16.dp),
                colors = CardDefaults.cardColors(containerColor = Color(0xFF131B2A)),
                modifier = Modifier.fillMaxWidth()
            ) {
                Column(
                    modifier = Modifier.padding(16.dp),
                    verticalArrangement = Arrangement.spacedBy(12.dp)
                ) {
                    Text(text = T.translate(lang, "request_amount"), fontWeight = FontWeight.SemiBold, color = Color.White, fontSize = 13.sp)

                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.spacedBy(8.dp)
                    ) {
                        OutlinedTextField(
                            value = requestAmount,
                            onValueChange = {
                                requestAmount = it
                                showCustomQr = it.isNotEmpty()
                            },
                            placeholder = { Text(text = "0.00", color = Color.White.copy(alpha = 0.3f)) },
                            keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Decimal),
                            colors = TextFieldDefaults.outlinedTextFieldColors(
                                focusedTextColor = Color.White,
                                unfocusedTextColor = Color.White,
                                focusedBorderColor = Color(0xFF007AFA),
                                unfocusedBorderColor = Color(0xFF1E293B)
                            ),
                            modifier = Modifier.weight(1.5f)
                        )

                        // Selector
                        Box(
                            modifier = Modifier
                                .weight(1f)
                                .height(56.dp)
                                .clip(RoundedCornerShape(4.dp))
                                .border(1.dp, Color(0xFF1E293B))
                                .background(Color(0xFF131B2A))
                                .clickable {
                                    selectedAssetSymbol = if (selectedAssetSymbol == "UXD") "USDT" else "UXD"
                                },
                            contentAlignment = Alignment.Center
                        ) {
                            Text(text = selectedAssetSymbol, color = Color(0xFF4FA9FB), fontWeight = FontWeight.Bold)
                        }
                    }

                    if (showCustomQr) {
                        Text(
                            text = "Código QR reconfigurado a cobro de $requestAmount $selectedAssetSymbol.",
                            color = Color(0xFF00FFCC),
                            fontSize = 12.sp,
                            fontWeight = FontWeight.SemiBold
                        )
                    }
                }
            }
        }
    }
}

@Composable
fun QrPaymentsScreen(viewModel: PesoWalletViewModel, modifier: Modifier = Modifier) {
    val lang by viewModel.currentLanguage.collectAsState()
    
    // Scanner Simulation Screen
    var scanCompleted by remember { mutableStateOf(false) }
    var detectedScenario by remember { mutableStateOf<String?>(null) } // "Peer", "Merchant", null

    Box(
        modifier = modifier
            .fillMaxSize()
            .background(Color(0xFF00050E))
            .windowInsetsPadding(WindowInsets.statusBars)
    ) {
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(16.dp),
            horizontalAlignment = Alignment.CenterHorizontally
        ) {
            // Header
            Row(
                modifier = Modifier.fillMaxWidth(),
                verticalAlignment = Alignment.CenterVertically
            ) {
                IconButton(onClick = { viewModel.navigateTo("dashboard") }) {
                    Icon(imageVector = Icons.Default.Close, contentDescription = "Close", tint = Color.White)
                }
                Spacer(modifier = Modifier.width(8.dp))
                Text(
                    text = T.translate(lang, "qr_scanner"),
                    style = MaterialTheme.typography.titleLarge.copy(fontWeight = FontWeight.Bold),
                    color = Color.White
                )
            }

            Spacer(modifier = Modifier.weight(0.2f))

            // Simulated Scanner target viewfinder box
            Box(
                modifier = Modifier
                    .size(240.dp)
                    .clip(RoundedCornerShape(32.dp))
                    .border(2.dp, Color(0xFF007AFA), RoundedCornerShape(32.dp))
                    .background(Color.White.copy(alpha = 0.05f)),
                contentAlignment = Alignment.Center
            ) {
                // Diagonal indicator line drawing representing live scanning laser!
                val infiniteTransition = rememberInfiniteTransition()
                val laserPosition by infiniteTransition.animateFloat(
                    initialValue = 0f,
                    targetValue = 1f,
                    animationSpec = infiniteRepeatable(
                        animation = tween(2000, easing = LinearEasing),
                        repeatMode = RepeatMode.Reverse
                    )
                )

                Canvas(modifier = Modifier.fillMaxSize()) {
                    val lineY = size.height * laserPosition
                    drawLine(
                        color = Color(0xFF00FFCC),
                        start = Offset(0f, lineY),
                        end = Offset(size.width, lineY),
                        strokeWidth = 3f
                    )
                }

                if (scanCompleted) {
                    Box(
                        modifier = Modifier
                            .clip(RoundedCornerShape(12.dp))
                            .background(Color.Black.copy(alpha = 0.8f))
                            .padding(16.dp)
                    ) {
                        Text(text = "¡QR Capturado!", color = Color(0xFF00FFCC), fontWeight = FontWeight.Bold)
                    }
                }
            }

            Spacer(modifier = Modifier.height(16.dp))

            Text(
                text = T.translate(lang, "scan_merchant_desc"),
                color = Color.White.copy(alpha = 0.5f),
                fontSize = 12.sp,
                textAlign = TextAlign.Center
            )

            Spacer(modifier = Modifier.weight(0.4f))

            // Quick Sim Buttons
            Text(text = "Click en un simulador de cobro para emular:", fontWeight = FontWeight.SemiBold, color = Color.White)
            Spacer(modifier = Modifier.height(8.dp))

            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.spacedBy(12.dp)
            ) {
                Button(
                    modifier = Modifier.weight(1f),
                    colors = ButtonDefaults.buttonColors(containerColor = Color(0xFF1E293B)),
                    onClick = {
                        scanCompleted = true
                        detectedScenario = "Peer"
                        viewModel.navigateTo("send") // Auto fill could go here, for simplicity we go Send!
                    }
                ) {
                    Text(text = "QR Amigo")
                }

                Button(
                    modifier = Modifier.weight(1f),
                    colors = ButtonDefaults.buttonColors(containerColor = Color(0xFF007AFA)),
                    onClick = {
                        scanCompleted = true
                        detectedScenario = "Merchant"
                        // Simulate merchant checkout payment
                        viewModel.navigateTo("merchant_dashboard")
                    }
                ) {
                    Text(text = "QR Local Cervecería")
                }
            }

            Spacer(modifier = Modifier.height(32.dp))
        }
    }
}
